"""
This type stub file was generated by pyright.
"""

import asyncio
import contextlib
import typing
import aiohttp
from typing import Optional, Union
from .api import TelegramAPIServer
from ..types import base
from ..utils.deprecated import deprecated

class BaseBot:
    """
    Base class for bot. It's raw bot.
    """
    _ctx_timeout = ...
    _ctx_token = ...
    def __init__(
            self,
            token: base.String,
            loop: Optional[Union[asyncio.BaseEventLoop, asyncio.AbstractEventLoop]] = ...,
            connections_limit: Optional[base.Integer] = ...,
            proxy: Optional[base.String] = ...,
            proxy_auth: Optional[aiohttp.BasicAuth] = ...,
            validate_token: Optional[base.Boolean] = ...,
            parse_mode: typing.Optional[base.String] = ...,
            timeout: typing.Optional[typing.Union[base.Integer, base.Float, aiohttp.ClientTimeout]] = ...,
            server: TelegramAPIServer = ...
    ):
        """
        Instructions how to get Bot token is found here: https://core.telegram.org/bots#3-how-do-i-create-a-bot

        :param token: token from @BotFather
        :type token: :obj:`str`
        :param loop: event loop
        :type loop: Optional Union :obj:`asyncio.BaseEventLoop`, :obj:`asyncio.AbstractEventLoop`
        :param connections_limit: connections limit for aiohttp.ClientSession
        :type connections_limit: :obj:`int`
        :param proxy: HTTP proxy URL
        :type proxy: :obj:`str`
        :param proxy_auth: Authentication information
        :type proxy_auth: Optional :obj:`aiohttp.BasicAuth`
        :param validate_token: Validate token.
        :type validate_token: :obj:`bool`
        :param parse_mode: You can set default parse mode
        :type parse_mode: :obj:`str`
        :param timeout: Request timeout
        :type timeout: :obj:`typing.Optional[typing.Union[base.Integer, base.Float, aiohttp.ClientTimeout]]`
        :param server: Telegram Bot API Server endpoint.
        :type server: :obj:`TelegramAPIServer`
        :raise: when token is invalid throw an :obj:`aiogram.utils.exceptions.ValidationError`
        """
        ...
    
    def get_new_session(self) -> aiohttp.ClientSession:
        ...
    
    @property
    def loop(self) -> ,:
        ...
    
    @property
    def session(self) -> ,:
        ...
    
    @property
    def timeout(self):
        ...
    
    @timeout.setter
    def timeout(self, value):
        ...
    
    @timeout.deleter
    def timeout(self):
        ...
    
    @contextlib.contextmanager
    def request_timeout(self, timeout: ,):
        """
        Context manager implements opportunity to change request timeout in current context

        :param timeout: Request timeout
        :type timeout: :obj:`typing.Optional[typing.Union[base.Integer, base.Float, aiohttp.ClientTimeout]]`
        :return:
        """
        ...
    
    @contextlib.contextmanager
    def with_token(self, bot_token: base.String, validate_token: , = ...):
        ...
    
    @deprecated("This method's behavior will be changed in aiogram v3.0. " "More info: https://core.telegram.org/bots/api#close", stacklevel=3)
    async def close(self):
        """
        Close all client sessions
        """
        ...
    
    async def request(self, method: base.String, data: , = ..., files: , = ..., **kwargs) -> ,:
        """
        Make an request to Telegram Bot API

        https://core.telegram.org/bots/api#making-requests

        :param method: API method
        :type method: :obj:`str`
        :param data: request parameters
        :type data: :obj:`dict`
        :param files: files
        :type files: :obj:`dict`
        :return: result
        :rtype: Union[List, Dict]
        :raise: :obj:`aiogram.exceptions.TelegramApiError`
        """
        ...
    
    async def download_file(self, file_path: base.String, destination: , = ..., timeout: , = ..., chunk_size: , = ..., seek: , = ...) -> ,:
        """
        Download file by file_path to destination

        if You want to automatically create destination (:class:`io.BytesIO`) use default
        value of destination and handle result of this method.

        :param file_path: file path on telegram server (You can get it from :obj:`aiogram.types.File`)
        :type file_path: :obj:`str`
        :param destination: filename or instance of :class:`io.IOBase`. For e. g. :class:`io.BytesIO`
        :param timeout: Integer
        :param chunk_size: Integer
        :param seek: Boolean - go to start of file when downloading is finished.
        :return: destination
        """
        ...
    
    def get_file_url(self, file_path):
        ...
    
    async def send_file(self, file_type, method, file, payload) -> ,:
        """
        Send file

        https://core.telegram.org/bots/api#inputfile

        :param file_type: field name
        :param method: API method
        :param file: String or io.IOBase
        :param payload: request payload
        :return: response
        """
        ...
    
    @property
    def parse_mode(self):
        ...
    
    @parse_mode.setter
    def parse_mode(self, value):
        ...
    
    @parse_mode.deleter
    def parse_mode(self):
        ...
    
    def check_auth_widget(self, data):
        ...
    


