"""
This type stub file was generated by pyright.
"""

JSON = 'json'
RAPIDJSON = 'rapidjson'
UJSON = 'ujson'
mode = JSON
if mode == RAPIDJSON:
    def dumps(data):
        ...
    
    def loads(data):
        ...
    
else:
    def loads(data):
        ...
    
    def dumps(data):
        ...
    
    def dumps(data):
        ...
    
    def loads(data):
        ...
    
