"""
This type stub file was generated by pyright.
"""

DEFAULT_FILTER = ['self', 'cls']
def generate_payload(exclude=..., **kwargs):
    """
    Generate payload

    Usage: payload = generate_payload(**locals(), exclude=['foo'])

    :param exclude:
    :param kwargs:
    :return: dict
    """
    ...

def prepare_arg(value):
    """
    Stringify dicts/lists and convert datetime/timedelta to unix-time

    :param value:
    :return:
    """
    ...

def prepare_file(payload, files, key, file):
    ...

def prepare_attachment(payload, files, key, file):
    ...

