"""
This type stub file was generated by pyright.
"""

import inspect
from contextvars import ContextVar
from dataclasses import dataclass
from typing import Iterable, Optional

ctx_data = ContextVar('ctx_handler_data')
current_handler = ContextVar('current_handler')
@dataclass
class FilterObj:
    filter: callable
    kwargs: dict
    is_async: bool
    ...


class SkipHandler(Exception):
    ...


class CancelHandler(Exception):
    ...


class Handler:
    def __init__(self, dispatcher, once=..., middleware_key=...) -> None:
        ...
    
    def register(self, handler, filters=..., index=...):
        """
        Register callback

        Filters can be awaitable or not.

        :param handler: coroutine
        :param filters: list of filters
        :param index: you can reorder handlers
        """
        ...
    
    def unregister(self, handler):
        """
        Remove handler

        :param handler: callback
        :return:
        """
        ...
    
    async def notify(self, *args):
        """
        Notify handlers

        :param args:
        :return:
        """
        ...
    
    @dataclass
    class HandlerObj:
        handler: callable
        spec: inspect.FullArgSpec
        filters: , = ...
    
    


