"""
This type stub file was generated by pyright.
"""

import typing
from . import base
from .message_entity import MessageEntity

class InputMessageContent(base.TelegramObject):
    """
    This object represents the content of a message to be sent as a result of an inline query.

    Telegram clients currently support the following 4 types

    https://core.telegram.org/bots/api#inputmessagecontent
    """
    ...


class InputContactMessageContent(InputMessageContent):
    """
    Represents the content of a contact message to be sent as the result of an inline query.

    Note: This will only work in Telegram versions released after 9 April, 2016.
    Older clients will ignore them.

    https://core.telegram.org/bots/api#inputcontactmessagecontent
    """
    phone_number: base.String = ...
    first_name: base.String = ...
    last_name: base.String = ...
    vcard: base.String = ...
    def __init__(self, phone_number: base.String, first_name: , = ..., last_name: , = ...) -> None:
        ...
    


class InputLocationMessageContent(InputMessageContent):
    """
    Represents the content of a location message to be sent as the result of an inline query.

    https://core.telegram.org/bots/api#inputlocationmessagecontent
    """
    latitude: base.Float = ...
    longitude: base.Float = ...
    horizontal_accuracy: , = ...
    live_period: , = ...
    heading: , = ...
    proximity_alert_radius: , = ...
    def __init__(self, latitude: base.Float, longitude: base.Float, horizontal_accuracy: , = ..., live_period: , = ..., heading: , = ..., proximity_alert_radius: , = ...) -> None:
        ...
    


class InputTextMessageContent(InputMessageContent):
    """
    Represents the content of a text message to be sent as the result of an inline query.

    https://core.telegram.org/bots/api#inputtextmessagecontent
    """
    message_text: base.String = ...
    parse_mode: base.String = ...
    disable_web_page_preview: base.Boolean = ...
    def safe_get_parse_mode(self):
        ...
    
    def __init__(self, message_text: , = ..., parse_mode: , = ..., caption_entities: , = ..., disable_web_page_preview: , = ...) -> None:
        ...
    


class InputVenueMessageContent(InputMessageContent):
    """
    Represents the content of a venue message to be sent as the result of an inline query.

    Note: This will only work in Telegram versions released after 9 April, 2016.
    Older clients will ignore them.

    https://core.telegram.org/bots/api#inputvenuemessagecontent
    """
    latitude: base.Float = ...
    longitude: base.Float = ...
    title: base.String = ...
    address: base.String = ...
    foursquare_id: base.String = ...
    foursquare_type: base.String = ...
    google_place_id: base.String = ...
    google_place_type: base.String = ...
    def __init__(self, latitude: , = ..., longitude: , = ..., title: , = ..., address: , = ..., foursquare_id: , = ..., foursquare_type: , = ..., google_place_id: , = ..., google_place_type: , = ...) -> None:
        ...
    


