"""
This type stub file was generated by pyright.
"""

import io
import typing
from . import base
from .input_file import InputFile
from .message_entity import MessageEntity

ATTACHMENT_PREFIX = 'attach://'
class InputMedia(base.TelegramObject):
    """
    This object represents the content of a media message to be sent. It should be one of
     - InputMediaAnimation
     - InputMediaDocument
     - InputMediaAudio
     - InputMediaPhoto
     - InputMediaVideo

    That is only base class.

    https://core.telegram.org/bots/api#inputmedia
    """
    type: base.String = ...
    media: base.String = ...
    thumb: , = ...
    caption: base.String = ...
    parse_mode: base.String = ...
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    @property
    def file(self):
        ...
    
    @file.setter
    def file(self, file: io.IOBase):
        ...
    
    @file.deleter
    def file(self):
        ...
    
    @property
    def thumb_file(self):
        ...
    
    @thumb_file.setter
    def thumb_file(self, file: io.IOBase):
        ...
    
    @thumb_file.deleter
    def thumb_file(self):
        ...
    
    def get_files(self):
        ...
    


class InputMediaAnimation(InputMedia):
    """
    Represents an animation file (GIF or H.264/MPEG-4 AVC video without sound) to be sent.

    https://core.telegram.org/bots/api#inputmediaanimation
    """
    width: base.Integer = ...
    height: base.Integer = ...
    duration: base.Integer = ...
    def __init__(self, media: base.InputFile, thumb: , = ..., caption: base.String = ..., width: base.Integer = ..., height: base.Integer = ..., duration: base.Integer = ..., parse_mode: base.String = ..., caption_entities: , = ..., **kwargs) -> None:
        ...
    


class InputMediaDocument(InputMedia):
    """
    Represents a general file to be sent.

    https://core.telegram.org/bots/api#inputmediadocument
    """
    def __init__(self, media: base.InputFile, thumb: , = ..., caption: base.String = ..., parse_mode: base.String = ..., caption_entities: , = ..., disable_content_type_detection: , = ..., **kwargs) -> None:
        ...
    


class InputMediaAudio(InputMedia):
    """
    Represents an audio file to be treated as music to be sent.

    https://core.telegram.org/bots/api#inputmediaaudio
    """
    duration: base.Integer = ...
    performer: base.String = ...
    title: base.String = ...
    def __init__(self, media: base.InputFile, thumb: , = ..., caption: base.String = ..., duration: base.Integer = ..., performer: base.String = ..., title: base.String = ..., parse_mode: base.String = ..., caption_entities: , = ..., **kwargs) -> None:
        ...
    


class InputMediaPhoto(InputMedia):
    """
    Represents a photo to be sent.

    https://core.telegram.org/bots/api#inputmediaphoto
    """
    def __init__(self, media: base.InputFile, caption: base.String = ..., parse_mode: base.String = ..., caption_entities: , = ..., **kwargs) -> None:
        ...
    


class InputMediaVideo(InputMedia):
    """
    Represents a video to be sent.

    https://core.telegram.org/bots/api#inputmediavideo
    """
    width: base.Integer = ...
    height: base.Integer = ...
    duration: base.Integer = ...
    supports_streaming: base.Boolean = ...
    def __init__(self, media: base.InputFile, thumb: , = ..., caption: base.String = ..., width: base.Integer = ..., height: base.Integer = ..., duration: base.Integer = ..., parse_mode: base.String = ..., caption_entities: , = ..., supports_streaming: base.Boolean = ..., **kwargs) -> None:
        ...
    


class MediaGroup(base.TelegramObject):
    """
    Helper for sending media group
    """
    def __init__(self, medias: , = ...) -> None:
        ...
    
    def attach_many(self, *medias: ,):
        """
        Attach list of media

        :param medias:
        """
        ...
    
    def attach(self, media: ,):
        """
        Attach media

        :param media:
        """
        ...
    
    def attach_photo(self, photo: ,, caption: base.String = ...):
        """
        Attach photo

        :param photo:
        :param caption:
        """
        ...
    
    def attach_video(self, video: ,, thumb: , = ..., caption: base.String = ..., width: base.Integer = ..., height: base.Integer = ..., duration: base.Integer = ...):
        """
        Attach video

        :param video:
        :param caption:
        :param width:
        :param height:
        :param duration:
        """
        ...
    
    def to_python(self) -> typing.List:
        """
        Get object as JSON serializable

        :return:
        """
        ...
    
    def get_files(self):
        ...
    


