"""
This type stub file was generated by pyright.
"""

import typing
from . import base

class Location(base.TelegramObject):
    """
    This object represents a point on the map.

    https://core.telegram.org/bots/api#location
    """
    longitude: base.Float = ...
    latitude: base.Float = ...
    horizontal_accuracy: , = ...
    live_period: , = ...
    heading: , = ...
    proximity_alert_radius: , = ...


