"""
This type stub file was generated by pyright.
"""

class Downloadable:
    """
    Mixin for files
    """
    async def download(self, destination=..., timeout=..., chunk_size=..., seek=..., make_dirs=...):
        """
        Download file

        :param destination: filename or instance of :class:`io.IOBase`. For e. g. :class:`io.BytesIO`
        :param timeout: Integer
        :param chunk_size: Integer
        :param seek: Boolean - go to start of file when downloading is finished.
        :param make_dirs: Make dirs if not exist
        :return: destination
        """
        ...
    
    async def get_file(self):
        """
        Get file information

        :return: :obj:`aiogram.types.File`
        """
        ...
    
    async def get_url(self):
        """
        Get file url.

        Attention!!
        This method has security vulnerabilities for the reason that result
        contains bot's *access token* in open form. Use at your own risk!

        :return: url
        """
        ...
    
    def __hash__(self) -> int:
        ...
    


