"""
This type stub file was generated by pyright.
"""

import typing
from . import base
from .photo_size import PhotoSize
from .sticker import Sticker

class StickerSet(base.TelegramObject):
    """
    This object represents a sticker set.

    https://core.telegram.org/bots/api#stickerset
    """
    name: base.String = ...
    title: base.String = ...
    is_animated: base.Boolean = ...
    contains_masks: base.Boolean = ...
    stickers: , = ...
    thumb: PhotoSize = ...


