"""
This type stub file was generated by pyright.
"""

class SysInfo:
    @property
    def os(self):
        ...
    
    @property
    def python_implementation(self):
        ...
    
    @property
    def python(self):
        ...
    
    @property
    def aiogram(self):
        ...
    
    @property
    def api(self):
        ...
    
    @property
    def uvloop(self):
        ...
    
    @property
    def ujson(self):
        ...
    
    @property
    def rapidjson(self):
        ...
    
    @property
    def aiohttp(self):
        ...
    
    def collect(self):
        ...
    
    def __str__(self) -> str:
        ...
    


if __name__ == '__main__':
    ...
